/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informedecompraventa;

import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.TreeMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucho
 */
public class PanelCargaComprobante extends javax.swing.JPanel {
    
        private DefaultTableModel tabla1;
        private DefaultTableModel tablaProd;
        HashSet<Alicuota> alics;
        private int fila;
        private static final TreeMap<Integer, Double> mapaIva = new TreeMap<Integer, Double>();
                static {
                    mapaIva.put(0, 0.0);
                    mapaIva.put(1, 0.105);
                    mapaIva.put(2, 0.21);
                    mapaIva.put(3, 0.27);
                    mapaIva.put(4, 0.05);
                    mapaIva.put(5, 0.025);
                }
        private double total;
        private String clave;
        private SimpleDateFormat Formato= new SimpleDateFormat("dd-MM-yyy");
    
        public String getFecha (JDateChooser jd){
        if (jd.getDate()!=null){
            return Formato.format(jd.getDate());
        }else return null;
    }
    
    
        
    /**
     * Creates new form Panel1
     */ 
        //ACA HICE MODIFICACION POR QUE LE PUSE EL TREEMAP
    public PanelCargaComprobante(String clave) {
       // TCaux= FramePrincipal.getTClientes();
        this.clave = clave;
        initComponents();
        initComp(this.clave);
        setName("Carga Comprabante");
    }
    
    public void vaciar()
    {
        initComponents();
        initComp(this.clave);
    }
    
    public boolean validarCampos(){
        boolean valido=true;
        if(jTextFieldNroComp1.getText()=="")
            valido=false;
        if(jTextFieldNroComp2.getText()=="")
            valido=false;
        if(fila<=0)
            valido=false;
        return valido;
    }
    
    public void initComp(String clave){
        
        tabla1 = (DefaultTableModel)jTable1.getModel();
        fila=0;
        jLabelNroID.setText(clave);
        
    }
    
    public void total(){
        total=0;
        if(fila>0){
            int i;
            for(i=0; i<jTableProductos.getRowCount();i++){
                total=total+(Double)jTableProductos.getValueAt(i, 3);
            }
            for(i=0; i<jTable1.getRowCount();i++){
                total=total+(Double)jTable1.getValueAt(i, 1);
            }
        }
        jLabelImporteTotal.setText(String.valueOf(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxCodID = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNroComp2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelImporteTotal = new javax.swing.JLabel();
        jTextFieldNroComp1 = new javax.swing.JTextField();
        jLabelNroID = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelNombreVend = new javax.swing.JLabel();
        jComboBoxCodTipo = new javax.swing.JComboBox<>();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBoxCodMoneda = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBoxCodOp = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldMonedaCambio = new javax.swing.JTextField();
        jFormattedTFFecha = new com.toedter.calendar.JDateChooser();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Conceptos Sin Precio Neto Gravado",  new Double(0.0)},
                {"Operaciones Exentas",  new Double(0.0)},
                {"Pagos Acuenta De Iva",  new Double(0.0)},
                {"Impuestos Nacionales",  new Double(0.0)},
                {"Impuestos Brutos",  new Double(0.0)},
                {"Impuestos Municipal",  new Double(0.0)},
                {"Impuestos Internos",  new Double(0.0)},
                {"Otros Tributos",  new Double(0.0)}
            },
            new String [] {
                "Atributo", "Monto: (Añadi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setBounds(220, 360, 400, 100);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }
        jTable1.getAccessibleContext().setAccessibleDescription("");

        add(jScrollPane1);
        jScrollPane1.setBounds(380, 160, 250, 160);

        jComboBoxCodID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "80 (CUIT)", "82 (CUIL)", "92 (en tramite)" }));
        jComboBoxCodID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxCodID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCodIDActionPerformed(evt);
            }
        });
        add(jComboBoxCodID);
        jComboBoxCodID.setBounds(210, 100, 100, 50);

        jButton1.setText("Agregar Importe");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(260, 330, 140, 30);

        jButton2.setText("Remover Importe");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(260, 360, 140, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0003 (0%)", "0004 (10.5%)", "0005 (21%)", "0006 (27%)", "0008 (5%)", "0009 (2.5%)" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox2.setMinimumSize(new java.awt.Dimension(90, 20));
        jComboBox2.setPreferredSize(new java.awt.Dimension(100, 20));
        add(jComboBox2);
        jComboBox2.setBounds(170, 360, 80, 30);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informacion del Comprobante");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel1);
        jLabel1.setBounds(210, 10, 270, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alicuota Asociado");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel2);
        jLabel2.setBounds(10, 360, 150, 30);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Añadir - Descripcion ", "Monto", "Alicuota", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableProductos);
        if (jTableProductos.getColumnModel().getColumnCount() > 0) {
            jTableProductos.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableProductos.getColumnModel().getColumn(1).setResizable(false);
            jTableProductos.getColumnModel().getColumn(2).setResizable(false);
            jTableProductos.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 160, 370, 160);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Numero de Comprobante");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel3);
        jLabel3.setBounds(210, 40, 270, 20);

        jTextFieldNroComp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNroComp2.setBorder(null);
        add(jTextFieldNroComp2);
        jTextFieldNroComp2.setBounds(270, 60, 210, 30);

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("$");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel4);
        jLabel4.setBounds(10, 430, 20, 32);

        jLabelImporteTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelImporteTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImporteTotal.setText("0,00");
        jLabelImporteTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "TOTAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jLabelImporteTotal.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabelImporteTotal);
        jLabelImporteTotal.setBounds(30, 420, 182, 40);

        jTextFieldNroComp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNroComp1.setText("00000");
        jTextFieldNroComp1.setBorder(null);
        jTextFieldNroComp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNroComp1ActionPerformed(evt);
            }
        });
        add(jTextFieldNroComp1);
        jTextFieldNroComp1.setBounds(210, 60, 50, 30);

        jLabelNroID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNroID.setText("Nro de Indentificacion");
        jLabelNroID.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelNroID.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabelNroID);
        jLabelNroID.setBounds(10, 120, 190, 30);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("_");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel7);
        jLabel7.setBounds(260, 60, 10, 30);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fecha de Emision");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel9);
        jLabel9.setBounds(490, 40, 140, 20);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Informacion del Cliente");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel8);
        jLabel8.setBounds(10, 10, 190, 20);

        jLabelNombreVend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreVend.setText("Nombre del Vendedor");
        jLabelNombreVend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelNombreVend.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabelNombreVend);
        jLabelNombreVend.setBounds(10, 60, 190, 30);

        jComboBoxCodTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura A", "Factura B", "Factura C" }));
        jComboBoxCodTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxCodTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCodTipoActionPerformed(evt);
            }
        });
        add(jComboBoxCodTipo);
        jComboBoxCodTipo.setBounds(490, 10, 140, 22);

        jFormattedTextField2.setBorder(null);
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setText("0,00");
        add(jFormattedTextField2);
        jFormattedTextField2.setBounds(170, 330, 80, 30);

        jComboBoxCodMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PES (Pesos)", "DOL (Dólares)", "060 (Euros)" }));
        jComboBoxCodMoneda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxCodMoneda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCodMonedaItemStateChanged(evt);
            }
        });
        add(jComboBoxCodMoneda);
        jComboBoxCodMoneda.setBounds(410, 350, 100, 40);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Importe Neto Gravado ");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel11);
        jLabel11.setBounds(10, 330, 150, 30);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("$");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel13);
        jLabel13.setBounds(160, 330, 10, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("GUARDAR COMPROBANTE");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(240, 410, 190, 50);

        jButton4.setText("Vaciar Campos");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(440, 410, 190, 30);

        jComboBoxCodOp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 (No Corresponde)", "A (No alcanzado)", "N (No gravado)", "X (Importación del Exterior)" }));
        jComboBoxCodOp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Codigo de Operacion"));
        add(jComboBoxCodOp);
        jComboBoxCodOp.setBounds(320, 100, 160, 50);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Moneda");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel12);
        jLabel12.setBounds(410, 330, 100, 20);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Indentificacion del Vendedor");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel14);
        jLabel14.setBounds(10, 100, 190, 20);

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(440, 440, 190, 30);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Nombre del Vendedor");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel15.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel15);
        jLabel15.setBounds(10, 40, 190, 20);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tipo de Cambio");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel16.setPreferredSize(new java.awt.Dimension(20, 20));
        add(jLabel16);
        jLabel16.setBounds(510, 330, 120, 20);

        jTextFieldMonedaCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMonedaCambio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jTextFieldMonedaCambio);
        jTextFieldMonedaCambio.setBounds(510, 350, 120, 40);

        jFormattedTFFecha.setDateFormatString("dd-MM-yyyy");
        add(jFormattedTFFecha);
        jFormattedTFFecha.setBounds(490, 60, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            //AGREGAR IMPORTE ... TENGO QUE HACER QUE SE AGREGUE A LA TABLA 
            double entero=0;
            String[] monton = jFormattedTextField2.getText().split(",");
            entero=Double.valueOf(monton[0].concat(monton[1]));
            entero=entero/100;
            //entero= Double.valueOf(jFormattedTextField2.getText().split(",").toString());
            //decimal= Double.valueOf(monton[1])/100;
            if(entero!=0){
                tablaProd = (DefaultTableModel)jTableProductos.getModel();
                tablaProd.addRow(new Object [4] );
                jTableProductos.setValueAt("",fila, 0);
                jTableProductos.setValueAt(mapaIva.get(jComboBox2.getSelectedIndex()),fila, 2);
                jTableProductos.setValueAt(entero,fila, 1);
                jTableProductos.setValueAt((1+mapaIva.get(jComboBox2.getSelectedIndex()))*
                        (Double)jTableProductos.getValueAt(fila, 1),
                        fila, 3);
                fila++;
                total();
                jFormattedTextField2.setText("0,00");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTableProductos.getSelectedRow()>-1){
            tablaProd.removeRow(jTableProductos.getSelectedRow());
            fila--;
            total();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxCodIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCodIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCodIDActionPerformed

    private void jComboBoxCodTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCodTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCodTipoActionPerformed

    private void jTextFieldNroComp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNroComp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNroComp1ActionPerformed
    public void crearComprobante(){
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(validarCampos()){
            int i;
            alics= new HashSet<Alicuota>();
            for(i=0; i<fila;i++){
                Alicuota a= new Alicuota();
                a.setDescripcion((String)jTableProductos.getValueAt(i, 0));
                a.setImporteNetoGravado((Double)jTableProductos.getValueAt(i, 1));
                a.setPorcentajeAsociado((Double)jTableProductos.getValueAt(i, 2));
                alics.add(a);
            }
            Double[] v= new Double[8];
            for(i=0; i<8; i++){
                v[i]=(Double)jTable1.getValueAt(i, 1);
            }
            
            Comprobante c = new Comprobante(getFecha(jFormattedTFFecha),jComboBoxCodTipo.getSelectedIndex(),
                    jTextFieldNroComp1.getText()+"-"+jTextFieldNroComp2.getText(),jComboBoxCodID.getSelectedIndex(),
                   jLabelNroID.getText(),jLabelNombreVend.getText(),Double.valueOf(jLabelImporteTotal.getText())
                    ,v[0],v[1],v[2],v[3],v[4],v[5],v[6],v[7],jComboBoxCodMoneda.getSelectedIndex(),0.0, 
                    jComboBoxCodOp.getSelectedIndex(),fila,alics);
            FramePrincipal.getTClientes().get(this.clave).getComprobante().add(c);
            jButton5ActionPerformed(evt);
       }
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       vaciar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        jTable1.clearSelection();
        total();
    }//GEN-LAST:event_jTable1FocusLost

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        total();
    }//GEN-LAST:event_jTable1FocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FramePrincipal.getEscritorio().removeAll();
        FramePrincipal.getEscritorio().repaint();
        VistaListaCliente vl= new VistaListaCliente(new PanelListaComprobante(this.clave));
        vl.setVisible(true);
        FramePrincipal.getEscritorio().add(vl);
        FramePrincipal.getEscritorio().moveToFront(vl);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
        total();
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jComboBoxCodMonedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCodMonedaItemStateChanged
        if(jComboBoxCodMoneda.getSelectedIndex()==0){
            jTextFieldMonedaCambio.setEditable(false);
            jTextFieldMonedaCambio.setText("1.0");
        }
        else{
            jTextFieldMonedaCambio.setEditable(true);
        }
    }//GEN-LAST:event_jComboBoxCodMonedaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxCodID;
    private javax.swing.JComboBox<String> jComboBoxCodMoneda;
    private javax.swing.JComboBox<String> jComboBoxCodOp;
    private javax.swing.JComboBox<String> jComboBoxCodTipo;
    private com.toedter.calendar.JDateChooser jFormattedTFFecha;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImporteTotal;
    private javax.swing.JLabel jLabelNombreVend;
    private javax.swing.JLabel jLabelNroID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldMonedaCambio;
    private javax.swing.JTextField jTextFieldNroComp1;
    private javax.swing.JTextField jTextFieldNroComp2;
    // End of variables declaration//GEN-END:variables
}
