/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informedecompraventa;

import java.awt.Color;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucho
 */
public class PanelCargaCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelCargaCliente
     */
    private String nombreCliente, apellidoCliente , cuitCliente, telefonoCliente;
    private String nombreComercio, direccComercio,cuitComercio,telefonoComercio;
    private Cliente cl;
    private Integer elegir;
    private ClienteComercio aux;
    //--------------------------------------------------------------------------
    public PanelCargaCliente() {
        initComponents();
              jLabelEcuit.setVisible(false);
              jLabel5NomC.setVisible(false);
              jLabelDire.setVisible(false);
              jLabelCuitComer.setVisible(false);
              jLabelTelCom.setVisible(false);
              jTextnombreComer.setVisible(false);
              jTextDireccion.setVisible(false);
              jTextCuitComer.setVisible(false);
              jTeTelComercio.setVisible(false);
              jLabelAviso.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCboxElegirCliente = new javax.swing.JComboBox<>();
        jLabelNom = new javax.swing.JLabel();
        jLabelApel = new javax.swing.JLabel();
        jLabelCuit = new javax.swing.JLabel();
        jTextCuitComer = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jLabel5NomC = new javax.swing.JLabel();
        jLabelDire = new javax.swing.JLabel();
        jLabelCuitComer = new javax.swing.JLabel();
        jLabelTelCom = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jTextApellido = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTeTelCliente = new javax.swing.JTextField();
        jTextCuitCliente = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextnombreComer = new javax.swing.JTextField();
        jTeTelComercio = new javax.swing.JTextField();
        jLabelAviso = new javax.swing.JLabel();
        jButCancel = new javax.swing.JButton();
        jLabelEcuit = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Cargar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 3, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setFont(new java.awt.Font("Candara", 3, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanel1.setLayout(null);

        jCboxElegirCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona", "Comercio" }));
        jCboxElegirCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jCboxElegirCliente.setMinimumSize(new java.awt.Dimension(69, 50));
        jCboxElegirCliente.setOpaque(false);
        jCboxElegirCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboxElegirClienteItemStateChanged(evt);
            }
        });
        jCboxElegirCliente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jCboxElegirClienteComponentMoved(evt);
            }
        });
        jCboxElegirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboxElegirClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jCboxElegirCliente);
        jCboxElegirCliente.setBounds(30, 40, 150, 30);

        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNom.setText("Nombre");
        jLabelNom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelNom);
        jLabelNom.setBounds(30, 90, 150, 20);

        jLabelApel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApel.setText("Apellido");
        jLabelApel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelApel);
        jLabelApel.setBounds(30, 150, 150, 20);

        jLabelCuit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCuit.setText("CUIT/CUIL");
        jLabelCuit.setToolTipText("");
        jLabelCuit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelCuit);
        jLabelCuit.setBounds(30, 210, 150, 20);

        jTextCuitComer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCuitComer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextCuitComer.setMinimumSize(new java.awt.Dimension(25, 25));
        jTextCuitComer.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextCuitComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCuitComerActionPerformed(evt);
            }
        });
        jTextCuitComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCuitComerKeyTyped(evt);
            }
        });
        jPanel1.add(jTextCuitComer);
        jTextCuitComer.setBounds(220, 230, 150, 30);

        jLabelTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTel.setText("Telefono");
        jLabelTel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelTel);
        jLabelTel.setBounds(30, 270, 150, 20);

        jLabel5NomC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5NomC.setText("Nombre del Comercio");
        jLabel5NomC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5NomC);
        jLabel5NomC.setBounds(220, 90, 150, 20);

        jLabelDire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDire.setText("Direccion del Comercio");
        jLabelDire.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelDire);
        jLabelDire.setBounds(220, 150, 150, 20);

        jLabelCuitComer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCuitComer.setText("CUIT del Comercio");
        jLabelCuitComer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelCuitComer);
        jLabelCuitComer.setBounds(220, 210, 150, 20);

        jLabelTelCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelCom.setText("Telefono del Comercio");
        jLabelTelCom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelTelCom);
        jLabelTelCom.setBounds(220, 270, 150, 20);

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuardar);
        jButtonGuardar.setBounds(220, 360, 150, 30);

        jTextApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextApellido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextApellido.setMinimumSize(new java.awt.Dimension(25, 25));
        jTextApellido.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellidoActionPerformed(evt);
            }
        });
        jTextApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(jTextApellido);
        jTextApellido.setBounds(30, 170, 150, 30);

        jTextNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextNombre.setMinimumSize(new java.awt.Dimension(25, 25));
        jTextNombre.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        jPanel1.add(jTextNombre);
        jTextNombre.setBounds(30, 110, 150, 30);

        jTeTelCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTeTelCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTeTelCliente.setMinimumSize(new java.awt.Dimension(25, 25));
        jTeTelCliente.setPreferredSize(new java.awt.Dimension(25, 25));
        jTeTelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeTelClienteActionPerformed(evt);
            }
        });
        jTeTelCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTeTelClienteKeyTyped(evt);
            }
        });
        jPanel1.add(jTeTelCliente);
        jTeTelCliente.setBounds(30, 290, 150, 30);

        jTextCuitCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCuitCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextCuitCliente.setMinimumSize(new java.awt.Dimension(25, 25));
        jTextCuitCliente.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextCuitCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCuitClienteActionPerformed(evt);
            }
        });
        jTextCuitCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCuitClienteKeyTyped(evt);
            }
        });
        jPanel1.add(jTextCuitCliente);
        jTextCuitCliente.setBounds(30, 230, 150, 30);

        jTextDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextDireccion.setMinimumSize(new java.awt.Dimension(25, 25));
        jTextDireccion.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDireccionActionPerformed(evt);
            }
        });
        jTextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDireccionKeyTyped(evt);
            }
        });
        jPanel1.add(jTextDireccion);
        jTextDireccion.setBounds(220, 170, 150, 30);

        jTextnombreComer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextnombreComer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextnombreComer.setMinimumSize(new java.awt.Dimension(25, 25));
        jTextnombreComer.setPreferredSize(new java.awt.Dimension(25, 25));
        jTextnombreComer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnombreComerActionPerformed(evt);
            }
        });
        jTextnombreComer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextnombreComerKeyTyped(evt);
            }
        });
        jPanel1.add(jTextnombreComer);
        jTextnombreComer.setBounds(220, 110, 150, 30);

        jTeTelComercio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTeTelComercio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTeTelComercio.setMinimumSize(new java.awt.Dimension(25, 25));
        jTeTelComercio.setPreferredSize(new java.awt.Dimension(25, 25));
        jTeTelComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTeTelComercioActionPerformed(evt);
            }
        });
        jTeTelComercio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTeTelComercioKeyTyped(evt);
            }
        });
        jPanel1.add(jTeTelComercio);
        jTeTelComercio.setBounds(220, 290, 150, 30);

        jLabelAviso.setForeground(new java.awt.Color(255, 0, 0));
        jLabelAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAviso.setText("Campo Obligatorio (*)");
        jPanel1.add(jLabelAviso);
        jLabelAviso.setBounds(30, 330, 150, 20);

        jButCancel.setText("Volver");
        jButCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButCancel);
        jButCancel.setBounds(30, 360, 150, 30);

        jLabelEcuit.setForeground(new java.awt.Color(255, 0, 0));
        jLabelEcuit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEcuit.setText("CUIT/CUIL Existente");
        jPanel1.add(jLabelEcuit);
        jLabelEcuit.setBounds(220, 330, 150, 20);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidoKeyTyped
        if(letraInvalida(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextApellidoKeyTyped

    private void jTextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellidoActionPerformed

    private void jTextnombreComerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnombreComerKeyTyped
        if(letraInvalida(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextnombreComerKeyTyped

    private void jTextnombreComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnombreComerActionPerformed

    }//GEN-LAST:event_jTextnombreComerActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        if(letraInvalida(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelActionPerformed
        FramePrincipal.getEscritorio().removeAll();
        FramePrincipal.getEscritorio().repaint();
        VistaListaCliente vl= new VistaListaCliente(new PanelListaClientes());
        vl.setVisible(true);
        FramePrincipal.getEscritorio().add(vl);
        FramePrincipal.getEscritorio().moveToFront(vl);
    }//GEN-LAST:event_jButCancelActionPerformed

    private void jCboxElegirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboxElegirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboxElegirClienteActionPerformed

    private void jCboxElegirClienteComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jCboxElegirClienteComponentMoved

    }//GEN-LAST:event_jCboxElegirClienteComponentMoved

    private void jCboxElegirClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboxElegirClienteItemStateChanged
        switch(jCboxElegirCliente.getSelectedIndex()){
            case 0:{
                jTextnombreComer.setVisible(false);
                jLabel5NomC.setVisible(false);
                jLabelDire.setVisible(false);
                jLabelCuitComer.setVisible(false);
                jLabelTelCom.setVisible(false);
                jTextDireccion.setVisible(false);
                jTextCuitComer.setVisible(false);
                jTeTelComercio.setVisible(false);
                break;

            }
            case 1:
            jLabel5NomC.setVisible(true);
            jLabelDire.setVisible(true);
            jLabelCuitComer.setVisible(true);
            jLabelTelCom.setVisible(true);
            jTextnombreComer.setVisible(true);
            jTextDireccion.setVisible(true);
            jTextCuitComer.setVisible(true);
            jTeTelComercio.setVisible(true);
            break;
        }
    }//GEN-LAST:event_jCboxElegirClienteItemStateChanged

    private void jTeTelClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTeTelClienteKeyTyped
        if(numInvalido(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTeTelClienteKeyTyped

    private void jTeTelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeTelClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeTelClienteActionPerformed

    private void jTextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDireccionKeyTyped
        if(letraInvalida(evt.getKeyChar()) && numInvalido(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextDireccionKeyTyped

    private void jTextDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDireccionActionPerformed

    }//GEN-LAST:event_jTextDireccionActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        resetLabels();
        if (JOptionPane.showConfirmDialog(null,"¿Esta seguro que desea cargar este cliente?")==0 && controlCarga()){
            if (jCboxElegirCliente.getSelectedIndex()==1){
                aux = (ClienteComercio) cargarClienteNuevo();
                FramePrincipal.getTClientes().put(aux.getCuitComercio(),aux);
            }else{
                FramePrincipal.getTClientes().put(cargarClienteNuevo().getCuit(),cargarClienteNuevo());
            }
            FramePrincipal.getEscritorio().removeAll();
            FramePrincipal.getEscritorio().repaint();
            VistaListaCliente vl= new VistaListaCliente(new PanelListaClientes());
            vl.setVisible(true);
            FramePrincipal.getEscritorio().add(vl);
            FramePrincipal.getEscritorio().moveToFront(vl);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextCuitComerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCuitComerKeyTyped
        if(numInvalido(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextCuitComerKeyTyped

    private void jTextCuitComerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCuitComerActionPerformed

    }//GEN-LAST:event_jTextCuitComerActionPerformed

    private void jTeTelComercioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTeTelComercioKeyTyped
        if(numInvalido(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTeTelComercioKeyTyped

    private void jTeTelComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTeTelComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTeTelComercioActionPerformed

    private void jTextCuitClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCuitClienteKeyTyped
        if(numInvalido(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_jTextCuitClienteKeyTyped

    private void jTextCuitClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCuitClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCuitClienteActionPerformed
     // METODO PARA VER QUE ONDA CON LOS JTEXT PARA QUE INGRESE BIEN LAS COSAS
    private boolean controlCarga(){
        boolean valido = true;
        if(jTextNombre.getText().equals("")){
            jLabelAviso.setVisible(true);
            jLabelNom.setForeground(Color.red);
            valido = false;
        }
        if(jTextApellido.getText().equals("")){
            jLabelAviso.setVisible(true);
            jLabelApel.setForeground(Color.red);
            valido = false;
        }
        if(jTextCuitCliente.getText().equals("")|| jTextCuitCliente.getText().length() != 11){
            jLabelCuit.setForeground(Color.red);
            valido = false;
        } else if (FramePrincipal.getTClientes().containsKey(jTextCuitCliente.getText()) && jCboxElegirCliente.getSelectedIndex()==0){
                jLabelCuit.setForeground(Color.red);
                jLabelEcuit.setVisible(true);
                valido = false;
            }
        if(jTeTelCliente.getText().equals("")){
            jLabelAviso.setVisible(true);
            jLabelTel.setForeground(Color.red);
            valido = false;
        }
        if(jCboxElegirCliente.getSelectedIndex()==1){
            if(jTextCuitComer.getText().equals("")|| jTextCuitComer.getText().length() != 11){
            jLabelCuitComer.setForeground(Color.red);
            valido = false;
            }else if (FramePrincipal.getTClientes().containsKey(jTextCuitComer.getText())){
                jLabelCuitComer.setForeground(Color.red);
                jLabelEcuit.setVisible(true);
                valido = false;
            }
            if(jTeTelComercio.getText().equals("")){
            jLabelTelCom.setForeground(Color.red);
            valido = false;
            jLabelAviso.setVisible(true);
            }
            if(jTextDireccion.getText().equals("")){
            jLabelDire.setForeground(Color.red);
            valido = false;
            jLabelAviso.setVisible(true);
            }
            if(jTextnombreComer.getText().equals("")){
            jLabel5NomC.setForeground(Color.red);
            valido = false;
            jTextnombreComer.setBackground(new java.awt.Color(255, 0, 0));
            jTextnombreComer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
            jTextnombreComer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            jLabelAviso.setVisible(true);
            }            
        }
         return valido;
    }
    private void resetLabels(){
        jLabelAviso.setVisible(false);
        jLabelEcuit.setVisible(false);
        jLabelNom.setForeground(Color.black);
        jLabelApel.setForeground(Color.black);
        jLabelTel.setForeground(Color.black);
        jLabel5NomC.setForeground(Color.black);
        jLabelCuit.setForeground(Color.black);
        jLabelCuitComer.setForeground(Color.black);
        jLabelDire.setForeground(Color.black);
        jLabelTelCom.setForeground(Color.black);
        
    }
    //METODO PARA QUE SOLO SE INGRESEN NUMEROS 
        public boolean numInvalido(char num){
            return (num<'0' || num>'9');
        }
    //METODO PARA QUE SOLO SE INGRESEN LETRAS
        public boolean letraInvalida(char letra){
        return ((letra<'a'||letra>'z'))&&((letra<'A'||letra>'Z')&& !(letra=='ñ' || letra =='Ñ') && letra!=' ');
        }
    //METODO PARA CARGAR CLIENTE 
    public Cliente cargarClienteNuevo(){
        
      if(jCboxElegirCliente.getSelectedIndex()==0){
          nombreCliente=jTextNombre.getText();
          apellidoCliente=jTextApellido.getText();
          cuitCliente=jTextCuitCliente.getText();
          telefonoCliente=jTeTelCliente.getText();
          cl = new Cliente(nombreCliente,apellidoCliente,cuitCliente,telefonoCliente);
          return cl;
      }else if(jCboxElegirCliente.getSelectedIndex()==1){
          nombreCliente=jTextNombre.getText();
          apellidoCliente=jTextApellido.getText();
          cuitCliente=jTextCuitCliente.getText();
          telefonoCliente=jTeTelCliente.getText();
          nombreComercio=jTextnombreComer.getText();
          direccComercio=jTextDireccion.getText();
          cuitComercio=jTextCuitComer.getText();
          telefonoComercio=jTeTelComercio.getText();
          cl = new ClienteComercio(nombreComercio,direccComercio,cuitComercio,telefonoComercio,nombreCliente,apellidoCliente,cuitCliente,telefonoCliente);
      }
      return cl;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButCancel;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jCboxElegirCliente;
    private javax.swing.JLabel jLabel5NomC;
    private javax.swing.JLabel jLabelApel;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelCuit;
    private javax.swing.JLabel jLabelCuitComer;
    private javax.swing.JLabel jLabelDire;
    private javax.swing.JLabel jLabelEcuit;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelTelCom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTeTelCliente;
    private javax.swing.JTextField jTeTelComercio;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCuitCliente;
    private javax.swing.JTextField jTextCuitComer;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextnombreComer;
    // End of variables declaration//GEN-END:variables
}
